"""
Curated canonical SQL examples drawn from Spider and WikiSQL benchmarks.
Categorized by pattern_type, complexity, and difficulty for ChromaDB retrieval.
"""

CANONICAL_SQL_EXAMPLES = [
    # ── AGGREGATION EXAMPLES (AVG, SUM, MIN, MAX, COUNT) ───────────────
    {
        "source": "spider",
        "question": "What is the average amount of all orders?",
        "sql": "SELECT avg(amount) FROM orders;",
        "pattern_type": "aggregation",
        "complexity": "simple",
        "has_aggregation": True,
    },
    {
        "source": "spider",
        "question": "What is the average price of products?",
        "sql": "SELECT avg(price) FROM products;",
        "pattern_type": "aggregation",
        "complexity": "simple",
        "has_aggregation": True,
    },
    {
        "source": "spider",
        "question": "Find the average salary of all employees.",
        "sql": "SELECT avg(salary) FROM employees;",
        "pattern_type": "aggregation",
        "complexity": "simple",
        "has_aggregation": True,
    },
    {
        "source": "wikisql",
        "question": "What is the average score of all players?",
        "sql": "SELECT avg(score) FROM players;",
        "pattern_type": "aggregation",
        "complexity": "simple",
        "has_aggregation": True,
    },
    {
        "source": "spider",
        "question": "What is the average age of customers?",
        "sql": "SELECT avg(age) FROM customers;",
        "pattern_type": "aggregation",
        "complexity": "simple",
        "has_aggregation": True,
    },
    {
        "source": "spider",
        "question": "What is the total amount of all orders?",
        "sql": "SELECT sum(amount) FROM orders;",
        "pattern_type": "aggregation",
        "complexity": "simple",
        "has_aggregation": True,
    },
    {
        "source": "spider",
        "question": "Find the total revenue from orders.",
        "sql": "SELECT sum(revenue) FROM orders;",
        "pattern_type": "aggregation",
        "complexity": "simple",
        "has_aggregation": True,
    },
    {
        "source": "spider",
        "question": "What is the minimum order amount?",
        "sql": "SELECT min(amount) FROM orders;",
        "pattern_type": "aggregation",
        "complexity": "simple",
        "has_aggregation": True,
    },
    {
        "source": "spider",
        "question": "What is the maximum order amount?",
        "sql": "SELECT max(amount) FROM orders;",
        "pattern_type": "aggregation",
        "complexity": "simple",
        "has_aggregation": True,
    },
    {
        "source": "spider",
        "question": "Find the lowest price among all products.",
        "sql": "SELECT min(price) FROM products;",
        "pattern_type": "aggregation",
        "complexity": "simple",
        "has_aggregation": True,
    },
    {
        "source": "spider",
        "question": "Find the highest salary among all employees.",
        "sql": "SELECT max(salary) FROM employees;",
        "pattern_type": "aggregation",
        "complexity": "simple",
        "has_aggregation": True,
    },
    {
        "source": "spider",
        "question": "How many orders are there in total?",
        "sql": "SELECT count(*) FROM orders;",
        "pattern_type": "aggregation",
        "complexity": "simple",
        "has_aggregation": True,
    },
    {
        "source": "spider",
        "question": "How many orders have been placed?",
        "sql": "SELECT count(*) FROM orders;",
        "pattern_type": "aggregation",
        "complexity": "simple",
        "has_aggregation": True,
    },
    {
        "source": "spider",
        "question": "Count the total number of customers.",
        "sql": "SELECT count(*) FROM customers;",
        "pattern_type": "aggregation",
        "complexity": "simple",
        "has_aggregation": True,
    },
    {
        "source": "spider",
        "question": "How many products are currently in stock?",
        "sql": "SELECT count(*) FROM products;",
        "pattern_type": "aggregation",
        "complexity": "simple",
        "has_aggregation": True,
    },

    # ── GROUP BY & AGGREGATIONS ─────────────────────────────────────────
    {
        "source": "spider",
        "question": "For each customer, show their total spending.",
        "sql": "SELECT customer_id, sum(amount) FROM orders GROUP BY customer_id;",
        "pattern_type": "group_by",
        "complexity": "medium",
        "has_aggregation": True,
    },
    {
        "source": "spider",
        "question": "Show the average order amount for each customer.",
        "sql": "SELECT customer_id, avg(amount) FROM orders GROUP BY customer_id;",
        "pattern_type": "group_by",
        "complexity": "medium",
        "has_aggregation": True,
    },
    {
        "source": "spider",
        "question": "Count the number of orders per customer.",
        "sql": "SELECT customer_id, count(*) FROM orders GROUP BY customer_id;",
        "pattern_type": "group_by",
        "complexity": "medium",
        "has_aggregation": True,
    },
    {
        "source": "spider",
        "question": "Show the total sales for each city.",
        "sql": "SELECT city, sum(sales) FROM stores GROUP BY city;",
        "pattern_type": "group_by",
        "complexity": "medium",
        "has_aggregation": True,
    },
    {
        "source": "spider",
        "question": "Find the average salary by department.",
        "sql": "SELECT department, avg(salary) FROM employees GROUP BY department;",
        "pattern_type": "group_by",
        "complexity": "medium",
        "has_aggregation": True,
    },
    {
        "source": "spider",
        "question": "Show departments with average salary greater than 50000.",
        "sql": "SELECT department, avg(salary) FROM employees GROUP BY department HAVING avg(salary) > 50000;",
        "pattern_type": "having",
        "complexity": "medium",
        "has_aggregation": True,
    },
    {
        "source": "spider",
        "question": "Show customers who placed more than 3 orders.",
        "sql": "SELECT customer_id, count(*) FROM orders GROUP BY customer_id HAVING count(*) > 3;",
        "pattern_type": "having",
        "complexity": "medium",
        "has_aggregation": True,
    },

    # ── MULTI-TABLE JOINS ───────────────────────────────────────────────
    {
        "source": "spider",
        "question": "Show customer names and their order amounts.",
        "sql": "SELECT T1.name, T2.amount FROM customers AS T1 JOIN orders AS T2 ON T1.customer_id = T2.customer_id;",
        "pattern_type": "join",
        "complexity": "medium",
        "join_count": 1,
        "join_type": "JOIN",
        "difficulty": "multi_table",
    },
    {
        "source": "spider",
        "question": "Find the top 3 customers by total spending with their names and cities.",
        "sql": "SELECT T1.name, T1.city, sum(T2.amount) AS total_spent FROM customers AS T1 JOIN orders AS T2 ON T1.customer_id = T2.customer_id GROUP BY T1.name, T1.city ORDER BY total_spent DESC LIMIT 3;",
        "pattern_type": "join",
        "complexity": "hard",
        "join_count": 1,
        "join_type": "JOIN",
        "has_aggregation": True,
        "difficulty": "multi_table",
    },
    {
        "source": "spider",
        "question": "List all products ordered with customer names.",
        "sql": "SELECT T1.name, T3.product_name FROM customers AS T1 JOIN orders AS T2 ON T1.customer_id = T2.customer_id JOIN order_items AS T3 ON T2.order_id = T3.order_id;",
        "pattern_type": "join",
        "complexity": "hard",
        "join_count": 2,
        "join_type": "JOIN",
        "difficulty": "advanced_multi_table",
    },

    # ── SUBQUERIES & COMPLEX REASONING ─────────────────────────────────
    {
        "source": "spider",
        "question": "Find customers whose total spending is greater than the average customer spending.",
        "sql": "SELECT customer_id, sum(amount) FROM orders GROUP BY customer_id HAVING sum(amount) > (SELECT avg(total_spent) FROM (SELECT sum(amount) AS total_spent FROM orders GROUP BY customer_id) AS sub);",
        "pattern_type": "subquery",
        "complexity": "hard",
        "has_aggregation": True,
        "has_subquery": True,
        "difficulty": "hard",
    },
    {
        "source": "spider",
        "question": "Find orders that have an amount higher than the average order amount.",
        "sql": "SELECT order_id, amount FROM orders WHERE amount > (SELECT avg(amount) FROM orders);",
        "pattern_type": "subquery",
        "complexity": "medium",
        "has_aggregation": True,
        "has_subquery": True,
        "difficulty": "medium",
    },

    # ── SELECT & FILTERS ───────────────────────────────────────────────
    {
        "source": "spider",
        "question": "List all customers from New York.",
        "sql": "SELECT * FROM customers WHERE city = 'New York';",
        "pattern_type": "select_where",
        "complexity": "simple",
    },
    {
        "source": "spider",
        "question": "Show the top 5 most expensive orders.",
        "sql": "SELECT * FROM orders ORDER BY amount DESC LIMIT 5;",
        "pattern_type": "select_where",
        "complexity": "simple",
    },
    {
        "source": "wikisql",
        "question": "Show all orders with amount greater than 100.",
        "sql": "SELECT * FROM orders WHERE amount > 100;",
        "pattern_type": "select_where",
        "complexity": "simple",
    }
]
