"""replace_filepath_with_temp_schema

Revision ID: d5d6c7e7a93b
Revises: 7b3492fe923b
Create Date: 2026-06-21 16:28:15.598429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5d6c7e7a93b'
down_revision: Union[str, Sequence[str], None] = '7b3492fe923b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('database_connections', sa.Column('schema_name', sa.String(length=127), nullable=False))
    op.add_column('database_connections', sa.Column('table_name', sa.String(length=127), nullable=False))
    op.add_column('database_connections', sa.Column('columns_json', sa.Text(), nullable=True))
    op.add_column('database_connections', sa.Column('row_count', sa.Integer(), nullable=False))
    op.add_column('database_connections', sa.Column('file_format', sa.String(length=10), nullable=False))
    op.drop_column('database_connections', 'filepath')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('database_connections', sa.Column('filepath', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_column('database_connections', 'file_format')
    op.drop_column('database_connections', 'row_count')
    op.drop_column('database_connections', 'columns_json')
    op.drop_column('database_connections', 'table_name')
    op.drop_column('database_connections', 'schema_name')
    # ### end Alembic commands ###
